version: '3.7'

services:
  jupyter:
    build:
      context: ./jupyter-server
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./project-files:/home/${NB_USER}/work
    environment:
      - NB_USER=${NB_USER}
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    user:
        root
    working_dir:
        /home/${NB_USER}/work
    restart: always

  postgres:
    image: postgres:12.1
    container_name: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_PLUGINS=tinymce dump-zip

# Sollte ordner sein und nicht Volume um daten verschicken zu k√∂nnen.
volumes:
    database:
        driver: local
